FROM openjdk:8-jdk-alpine
ENV LIPPU_HOME=/home/lippu
MAINTAINER Markku Korkeala

ARG jar="lippu-service.jar"

ENV JARFILE=$jar

RUN adduser -S lippu
USER lippu
WORKDIR $LIPPU_HOME

COPY gradlew $LIPPU_HOME
COPY build.gradle $LIPPU_HOME
COPY gradle $LIPPU_HOME/gradle
COPY settings.gradle $LIPPU_HOME
RUN /bin/sh gradlew --continue clean compileJava