FROM lippu/lippu-builddeps

ENV LIPPU_HOME=/home/lippu
MAINTAINER Markku Korkeala

ARG jar="lippu-service.jar"

ENV JARFILE=$jar

USER lippu
COPY src $LIPPU_HOME/src
COPY build.sh $LIPPU_HOME

RUN sh build.sh